# Generated by Django 3.2.25 on 2024-09-23 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20240902_0003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'managed': True, 'permissions': [('change_only_yours', 'Pode mudar apenas seus dados de Feedback'), ('feedback_list', 'Pode Listar todos Feedbacks na API'), ('feedback_retrieve', 'Pode recuperar um registro Feedbacks na API'), ('feedback_update', 'Pode atualizar Feedbacks na API'), ('feedback_partial_update', 'Pode atualizar parcialmente Feedbacks na API'), ('feedback_create', 'Pode criar Feedbacks na API'), ('feedback_destroy', 'Pode destruir Feedbacks na API')]},
        ),
    ]
